export ZSH="$HOME/.oh-my-zsh"

plugins=(
git
thefuck
zsh-autosuggestions
zsh-syntax-highlighting
)

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#22242a,underline"

alias c="clear"
alias cat="bat --color always --plain"
alias du="duf"
alias ls="exa"
alias find="fd"
alias nf="neofetch"
alias vi="nvim"
alias nv="nvim"
alias mv="mv -v"
alias cp="cp -vr"
alias rm="rm -vr"

source $ZSH/oh-my-zsh.sh

export PATH="/opt/homebrew/opt/curl/bin:$PATH"

export PATH=$PATH:/Users/dill/.local/bin
export PATH=$PATH:/Users/dill/.spicetify

eval "$(starship init zsh)"
export STARSHIP_CONFIG=$HOME/.config/starship/starship.toml
